spring:
  application:
    name: 63-Spring-Security-JDBC-Auth-App
  datasource:
    url: jdbc:mysql://localhost:3306/sbms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vaibhav
    password: vaibhav
  jpa:
    show-sql: true
  main:
    banner-mode: console
server:
  port: 8081