server:
  port: 8081
spring:
  application:
    name: 57-Config-Server-App
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaibhav756/SBMS
          clone-on-start: true
  main:
    banner-mode: console
