spring:
  application:
    name: SPRING-SECURITY-OAUTH
  main:
    banner-mode: console
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${Client_Id}
            client-secret: ${Client_Secret}
          google: 
            client-id: ${Google_Client_Id}
            client-secret: ${Google_Client_Secret}
server:
  port: 8081 