spring:
  main:
    banner-mode: console
  boot:
    admin:
      client:
        url: http://localhost:1111/
  application:
    name: Eureka-Client-Greet-Api
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true